### PR TITLE
fix(js): set spans from instrumentation active span on context in OpenAI instrumentor

### LINKED ISSUE #1061: [feature request] JS example with HttpInstrumentation
**Is your feature request related to a problem? Please describe.**

I have an local example which uses OpenAI and HttpInstrumentation, but the http spans for the OpenAI calls seem to be in separate traces.

**Describe the solution you'd like**

I'd like an example which registers the normal HttpInstrumentation and is verified to create sub-spans, not new traces.

**Describe alternatives you've considered**

Just not using HttpInstrumentation

**Additional context**

### PR DESCRIPTION
**Pull request by Parker-Stafford**
resolves #1061 

- spans created as apart of the work instrumented in the OpenAIInstrumetation will now be properly nested under those spans, for example http instrumentation see:

image

### CODE REVIEW

**Review by cephalization — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
looking forward to helping q/a this once released!

**Comment by Parker-Stafford** [comment]
> looking forward to helping q/a this once released!

Awesome, have another fix to get in then should be releasing soon!

**Comment by codefromthecrypt** [comment]
sorry for the very late Q/A, this works now!

Screenshot 2025-01-18 at 7 58 43 AM

**Comment by Parker-Stafford** [comment]
> sorry for the very late Q/A, this works now!
> 
> Screenshot 2025-01-18 at 7 58 43 AM

No problem! Glad it's working for ya!

**Pull request merged**
