### PR TITLE
Docs - Add example using LiteLLM Proxy to call 100+ LLMs & Log to Arize 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Doc - Add example on using LiteLLM Proxy with Arize AI

Hi, I'm the maintainer of [LiteLLM](https://github.com/BerriAI/litellm) - made a PR to show how to use LiteLLM Proxy with Arize AI

## Why use LiteLLM Proxy ? 
Use [LiteLLM Proxy](https://docs.litellm.ai/docs/simple_proxy) for:
- Calling 100+ LLMs OpenAI, Azure, Vertex, Bedrock/etc. in the OpenAI ChatCompletions & Completions format
- Automatically Log all requests to Arize AI
- Proving a central self hosted server for calling LLMs + logging to Arize

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ishaan-jaff** [comment]
Can I get a review on this @axiomofjoy @mikeldking ?

**Comment by axiomofjoy** [comment]
@ishaan-jaff Will take a look, thanks!

**Review by shreyabsridhar — CHANGES_REQUESTED** [review]
Hi, it looks like you are working off of an older version of our repo. Please rebase and resolve any merge conflicts if needed.

Additionally, we have created an auto-instrumentor [here](https://github.com/Arize-ai/openinference/tree/main/python/instrumentation/openinference-instrumentation-litellm) that instruments liteLLM function calls. Please use this in any README walkthroughs or demos to be consistent with the rest of our repo and to avoid any potential confusion for the user. Thank you!

**Pull request closed without merging**
