### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by ShreyaR**

### CODE REVIEW

**Review by axiomofjoy — APPROVED** [review]

**Comment by axiomofjoy** [comment]
Thanks @ShreyaR! Can you follow the instructions above to sign the CLA?

**Comment by ShreyaR** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ShreyaR** [comment]
recheck

**Comment by mikeldking** [comment]
Thanks @ShreyaR !

**Pull request merged**
